"""add access option

Revision ID: a36943344e65
Revises: a8d659300257
Create Date: 2019-08-11 20:40:16.317354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36943344e65'
down_revision = 'a8d659300257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_access')
    # ### end Alembic commands ###
